services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: myparcelcom/final-mile-tracking:v1-dev
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - composercache:/.composer/cache

volumes:
  composercache:
    driver: local
